version: '3.8'

services:
  webapi:
    image: companymanager
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - database
    environment:
      ASPNETCORE_ENVIRONMENT: "Release"

  database:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
